version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - npm install
      - pip install --user aws-sam-cli awscli

  build:
    commands:
      - echo "Building Lambda function..."
      - npm run build --if-present
      - echo "Packaging Lambda function..."
      - cd dist
      - zip -r lambda.zip .
      - cd ..
      - echo "Running SAM package to generate packaged template..."
      - sam package --region us-west-2 --s3-prefix lambdas --template-file template.yaml --s3-bucket my-lambda-store-for-pipeline --use-json > packaged.json
      - echo "Extracting CodeUri from packaged.json..."
      - CODE_URI=$(cat packaged.json | python3 -c "import sys, json; print(json.load(sys.stdin)['Resources']['MyLambdaFunction']['Properties']['CodeUri'])")
      - echo "CodeUri is ${CODE_URI}"

artifacts:
  files:
    - appspec.yml
    - dist/lambda.zip
  discard-paths: yes
