version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - npm install
      - pip install --user aws-sam-cli  # Ensure AWS SAM is installed

  build:
    commands:
      - echo "Building Lambda function..."
      - npm run build --if-present
      - echo "Packaging Lambda function..."
      - cd dist
      - zip -r lambda.zip .
      - cd ..
      - sam package --region us-west-2 --template-file template.yaml --output-template-file packaged.yaml --s3-bucket my-lambda-store-for-pipeline
      - echo "Retrieving the latest Lambda function version..."
      - CURRENT_VERSION=$(aws lambda list-versions-by-function --region us-west-2 --function-name MyLambdaFunction --query 'Versions[-1].Version' --output text)
      - TARGET_VERSION=$((CURRENT_VERSION + 1))
      - echo "Generating dynamic appspec.yml for CodeDeploy..."
      - |
        cat <<EOT > appspec.yml
        version: 0.0
        Resources:
          - MyLambdaFunction:
              Type: AWS::Lambda::Function
              Properties:
                Name: MyLambdaFunction
                Alias: live
                CurrentVersion: $CURRENT_VERSION
                TargetVersion: $TARGET_VERSION
        EOT


  post_build:
    commands:
      - echo "Deploying Lambda function..."
      - sam deploy --region us-west-2 --template-file packaged.yaml --stack-name MyLambdaStack --capabilities CAPABILITY_IAM

artifacts:
  files:
    - packaged.yaml
    - appspec.yml
    - dist/lambda.zip
  discard-paths: yes


