version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - npm install
      - pip install --user aws-sam-cli awscli
      - yum install jq

  build:
    commands:
      - echo "Building Lambda function..."
      - npm run build --if-present
      - echo "Packaging Lambda function..."
      - cd dist
      - zip -r lambda.zip .
      - cd ..
      - echo "Running SAM package to generate packaged template..."
      - sam package --region us-west-2 --s3-prefix lambdas --template-file template.yaml --s3-bucket my-lambda-store-for-pipeline --use-json > packaged.json

artifacts:
  files:
    - packaged.json
    - appspec.yml
    - dist/lambda.zip
  discard-paths: yes
