version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - npm install
      - pip install --user aws-sam-cli  # Ensure AWS SAM is installed

  build:
    commands:
      - echo "Building Lambda function..."
      - npm run build --if-present
      - echo "Packaging Lambda function..."
      - cp appspec.yml ./dist/
      - ls -ltr ./dist/
      - cd dist
      - zip -r lambda.zip .
      - cd ..
      - sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket my-lambda-store-for-pipeline

  post_build:
    commands:
      - echo "Deploying Lambda function..."
      - sam deploy --template-file packaged.yaml --stack-name MyLambdaStack --capabilities CAPABILITY_IAM

artifacts:
  files:
    - packaged.yaml
    - appspec.yml
    - dist/lambda.zip

  discard-paths: yes


