version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - npm install
      - pip install --user aws-sam-cli awscli

  pre_build:
    commands:
      - LAMBDA_BUCKET=my-lambda-store-for-pipeline
      - FUNCTION_NAME=MyLambdaFunction
      - LAMBDA_STACK_NAME=MyLambdaStack
      - ALIAS=live

      - echo "Compile Lambda function..."
      - npm run build
      - echo "Package the function..."
      - npm run package

  build:
    commands:
      - echo "Push compiled code to S3. Generate SAM template with new s3://CodeUri ."
      - sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket ${LAMBDA_BUCKET}
      - echo "Deploy (create/update) the Lambda function..."
      - sam deploy --template-file packaged.yaml --stack-name ${LAMBDA_STACK_NAME} --capabilities CAPABILITY_IAM

  post_build:
    commands:
      - echo "Retrieving the latest Lambda function version..."
      - CURRENT_VERSION=$(aws lambda list-versions-by-function --region us-west-2 --function-name ${FUNCTION_NAME} --query 'Versions[-1].Version' --output text)
      - echo "Current Version = $CURRENT_VERSION"
      - echo "Generate appspec.yml for CodeDeploy..."
      - |
        cat <<EOT > appspec.yml
        version: 0.0
        Resources:
          - ${FUNCTION_NAME}:
              Type: AWS::Lambda::Function
              Properties:
                Name: ${FUNCTION_NAME}
                Alias: ${ALIAS}
                CurrentVersion: $CURRENT_VERSION
                TargetVersion: $CURRENT_VERSION
        EOT

artifacts:
  files:
    - appspec.yml
    - dist/lambda.zip
  discard-paths: yes
