version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - npm install
      - pip install --user aws-sam-cli awscli

  build:
    commands:
      - echo "Building Lambda function..."
      - npm run build --if-present
      - echo "Packaging Lambda function..."
      - cd dist
      - zip -r lambda.zip .
      - cd ..

artifacts:
  files:
    - dist/lambda.zip
  discard-paths: yes
