AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MyLambdaFunction
      Runtime: nodejs18.x
      Handler: index.handler
      CodeUri: ./dist/lambda.zip
      MemorySize: 128
      Timeout: 10
      Role: arn:aws:iam::009072398085:role/MyLambdaBasicExecutionRole
      AutoPublishAlias: live

Outputs:
  MyLambdaFunctionArn:
    Value: !Ref MyLambdaFunction
